### ISSUE TITLE
输入法光标跟随

### ISSUE THREAD

**Issue by hiforrest** [xuqinjie/markdownmate#1]
有时候输入法不跟随光标。

win7 64 sp1
搜狗拼音
![Uploading 图像2016-03-05-005.png…]()

**Comment by xuqinjie** [comment]
能再现吗？这个不太好确定，因为搜狗输入法本身也是有问题的，在某些版本中，如果在多种输入法之间切换过，搜狗就不会再跟随，需要重新启动这个进程。
