### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by cloudfox2** [xuqinjie/markdownmate#2]
**win7 MM1.2.2**

1. 预览中
![1](https://cloud.githubusercontent.com/assets/17975497/14249206/3c1afeae-faab-11e5-83f6-8b0acddd1a0d.png)
2. 
![2](https://cloud.githubusercontent.com/assets/17975497/14249221/5375d308-faab-11e5-99c7-547c829be035.png)
3. 更多字体样式里上标和下标效果反了
4. 重点强调(三个等于号)的效果作用在上一行?
5. 开着预览, 有序列表内没内容直接回车, 序号自动消失后一两秒就崩溃了
6. 最大化时预览窗口的滑动条只显示大概左边2/3
7. 估摸着ie也有点问题然后更新了下ie11(原来ie8), 问题1和5是没了, 但是为什么预览里的字带上阴影了..
![3](https://cloud.githubusercontent.com/assets/17975497/14251450/aebf1530-fab5-11e5-959f-bf8d72f77749.png)

**Comment by xuqinjie** [comment]
>更多字体样式里上标和下标效果反了
多谢，这个bug已修正，将会在新版中发布。

>最大化时预览窗口的滑动条只显示大概左边2/3
很遗憾，这个是IE的滚动条，它的高度目前还无法设置。

>7
字体带阴影，是默认的效果，目前如果不喜欢的话，只能手动修改，打开libs\preview.html, 找到
text-shadow这一行，删掉即可，
