### ISSUE TITLE
同一行中出现多个下标不能正常解析

### ISSUE THREAD

**Issue by atbest** [xuqinjie/markdownmate#6]
比如 `H~2~O~2~` 应该是 H<sub>2</sub>O<sub>2</sub>，但是现在解析成了 H<sub>2~O~2</sub>，应该把 marked.js 571-572 行改成：
```
  sup: /^\^(.+?)\^/,
  sub: /^~(.+?)~/,
```

**Comment by xuqinjie** [comment]
多谢。
